-- Relationale Datenbankstruktur fuer den Lebenslauf (PostgreSQL / Supabase)
-- Ausfuehren im Supabase SQL Editor

create table if not exists public.persons (
  id bigint generated by default as identity primary key,
  full_name text not null,
  job_title text,
  email text,
  phone text,
  location text,
  created_at timestamptz not null default now()
);

create table if not exists public.cv_sections (
  id bigint generated by default as identity primary key,
  person_id bigint not null references public.persons(id) on delete cascade,
  section_key text not null,
  title text not null,
  sort_order integer not null default 0
);

-- Mehrere Textvarianten pro Abschnitt -> bei jedem Request kann ein anderer Text kommen
create table if not exists public.cv_text_variants (
  id bigint generated by default as identity primary key,
  section_id bigint not null references public.cv_sections(id) on delete cascade,
  content text not null,
  is_active boolean not null default true
);

-- Strukturierte Eintraege (Ausbildung, Erfahrung, Skills)
create table if not exists public.cv_items (
  id bigint generated by default as identity primary key,
  section_id bigint not null references public.cv_sections(id) on delete cascade,
  headline text not null,
  subline text,
  description text,
  period_from text,
  period_to text,
  sort_order integer not null default 0
);

-- Beispieldaten (Yousef Sheii – 4DHIT, TGM Wien)
insert into public.persons (full_name, job_title, email, phone, location)
select 'Yousef Sheii', 'Schueler 4DHIT – Informationstechnik', 'yousefsheik2@icloud.com', '+43 660 0000000', 'Wien, Oesterreich (TGM)'
where not exists (select 1 from public.persons limit 1);

with p as (select id from public.persons order by id limit 1)
insert into public.cv_sections (person_id, section_key, title, sort_order)
select p.id, v.section_key, v.title, v.sort_order
from p
cross join (
  values
    ('about', 'Profil', 1),
    ('experience', 'Berufserfahrung', 2),
    ('education', 'Ausbildung', 3),
    ('skills', 'Kenntnisse', 4)
) as v(section_key, title, sort_order)
where not exists (select 1 from public.cv_sections limit 1);

-- Profil: 3 Varianten (zufaellig bei jedem Laden)
insert into public.cv_text_variants (section_id, content, is_active)
select s.id, v.content, true
from public.cv_sections s
cross join (
  values
    ('Ich bin Yousef Sheii aus der 4DHIT am TGM und entwickle gerne Web-Apps mit Datenbankanbindung.'),
    ('Mein Schwerpunkt liegt auf Java, Webentwicklung und strukturierten IT-Projekten in SEW und ITP.'),
    ('Ich arbeite zuverlaessig im Team, dokumentiere meine Projekte und setze Anforderungen Schritt fuer Schritt um.')
) as v(content)
where s.section_key = 'about'
  and not exists (select 1 from public.cv_text_variants limit 1);

insert into public.cv_items (section_id, headline, subline, description, period_from, period_to, sort_order)
select s.id, v.headline, v.subline, v.description, v.period_from, v.period_to, v.sort_order
from public.cv_sections s
cross join (
  values
    ('experience', 'ITP-Projekt: Lebenslauf mit Datenbank', 'TGM Wien', 'Web-App mit Supabase, relationalem Schema und GET-API /api/cv', '2026', '2026', 1),
    ('experience', 'SEW-Projekte (Java)', 'GitHub', 'Expressions, FileSystem-Watcher und objektorientierte Programmierung', '2025', '2026', 2),
    ('experience', 'Roblox FIFA WM 2026', 'Eigenes Spiel', 'Lua-Skripte: Wetter, NPCs, Minispiele, Lootboxen und Stadion-Systeme', '2026', '2026', 3),
    ('education', 'TGM – Die Schule der Technik', 'Klasse 4DHIT', 'Informationstechnik, 4. Jahrgang', '2022', '2026', 1),
    ('education', 'Schwerpunkt Softwareentwicklung', 'HTL', 'Web, Datenbanken, Programmierung und Projektarbeit', '2022', '2026', 2),
    ('skills', 'HTML, CSS, JavaScript', 'Frontend', 'Responsive Websites und API-Anbindung', '', '', 1),
    ('skills', 'SQL / PostgreSQL (Supabase)', 'Datenbank', 'Relationale Tabellen, JOINs, SELECT-Requests', '', '', 2),
    ('skills', 'Java, Lua, Git, Vercel', 'Programmierung & Tools', 'SEW-Projekte, Roblox Studio, Deployment', '', '', 3)
) as v(section_key, headline, subline, description, period_from, period_to, sort_order)
where s.section_key = v.section_key
  and not exists (select 1 from public.cv_items limit 1);
