-- ============================================================
-- VOLLSTAENDIGE DATENBANK – einmal im Supabase SQL Editor ausfuehren
-- Erstellt Tabellen, fuellt ALLE Daten, setzt Rechte
-- ============================================================

-- Tabellen (falls noch nicht vorhanden)
create table if not exists public.persons (
  id bigint generated by default as identity primary key,
  full_name text not null,
  job_title text,
  email text,
  phone text,
  location text,
  created_at timestamptz not null default now()
);

create table if not exists public.cv_sections (
  id bigint generated by default as identity primary key,
  person_id bigint not null references public.persons(id) on delete cascade,
  section_key text not null,
  title text not null,
  sort_order integer not null default 0
);

create table if not exists public.cv_text_variants (
  id bigint generated by default as identity primary key,
  section_id bigint not null references public.cv_sections(id) on delete cascade,
  content text not null,
  is_active boolean not null default true
);

create table if not exists public.cv_items (
  id bigint generated by default as identity primary key,
  section_id bigint not null references public.cv_sections(id) on delete cascade,
  headline text not null,
  subline text,
  description text,
  period_from text,
  period_to text,
  sort_order integer not null default 0
);

-- Alte Daten loeschen (CASCADE loescht alle verknuepften Tabellen)
truncate table public.persons restart identity cascade;

-- Person
insert into public.persons (full_name, job_title, email, phone, location)
values (
  'Yousef Sheii',
  'Schueler 4DHIT – Informationstechnik',
  'yousefsheik2@icloud.com',
  '+43 660 0000000',
  'Wien, Oesterreich (TGM)'
);

-- Abschnitte
insert into public.cv_sections (person_id, section_key, title, sort_order)
select p.id, v.section_key, v.title, v.sort_order
from public.persons p
cross join (
  values
    ('about',       'Profil',           1),
    ('experience',  'Berufserfahrung',  2),
    ('education',   'Ausbildung',       3),
    ('skills',      'Kenntnisse',       4),
    ('languages',   'Sprachen',         5)
) as v(section_key, title, sort_order)
where p.id = (select id from public.persons order by id limit 1);

-- Profil: 5 Textvarianten (bei jedem Reload anderer Text moeglich)
insert into public.cv_text_variants (section_id, content, is_active)
select s.id, v.content, true
from public.cv_sections s
cross join (
  values
    ('Ich bin Yousef Sheii aus der 4DHIT am TGM und entwickle Web-Apps mit relationaler Datenbank.'),
    ('Mein Schwerpunkt liegt auf Java, Webentwicklung und strukturierten IT-Projekten in SEW und ITP.'),
    ('Ich arbeite zuverlaessig im Team, dokumentiere Projekte und setze Anforderungen Schritt fuer Schritt um.'),
    ('Besonders interessiert mich die Verbindung von Frontend, API und PostgreSQL/Supabase.'),
    ('Mein Ziel ist eine Ausbildung im IT-Bereich mit Fokus auf Softwareentwicklung.')
) as v(content)
where s.section_key = 'about';

-- Berufserfahrung / Projekte
insert into public.cv_items (section_id, headline, subline, description, period_from, period_to, sort_order)
select s.id, v.headline, v.subline, v.description, v.period_from, v.period_to, v.sort_order
from public.cv_sections s
cross join (
  values
    ('experience', 'ITP: Lebenslauf mit Datenbank', 'TGM Wien',
     'Web-App mit Supabase, relationalem Schema, GET /api/cv und Vercel-Deployment', '2026', '2026', 1),
    ('experience', 'SEW: Java-Projekte', 'GitHub (Yousefsheii)',
     'Expressions, FileSystem-Watcher, OOP und Versionskontrolle mit Git', '2025', '2026', 2),
    ('experience', 'Roblox FIFA WM 2026', 'Lua / Roblox Studio',
     'Wetter, Tag/Nacht, Tore, NPCs, Minispiele, Lootboxen, Zonen-Teleport', '2026', '2026', 3),
    ('experience', 'Web-Projekte', 'HTML, CSS, JavaScript',
     'Responsive Websites, API-Anbindung und Deployment', '2025', '2026', 4)
) as v(section_key, headline, subline, description, period_from, period_to, sort_order)
where s.section_key = 'experience';

-- Ausbildung
insert into public.cv_items (section_id, headline, subline, description, period_from, period_to, sort_order)
select s.id, v.headline, v.subline, v.description, v.period_from, v.period_to, v.sort_order
from public.cv_sections s
cross join (
  values
    ('education', 'TGM – Die Schule der Technik', 'Klasse 4DHIT',
     'Informationstechnik, 4. Jahrgang', '2022', '2026', 1),
    ('education', 'Schwerpunkt Softwareentwicklung', 'HTL',
     'Programmierung, Datenbanken, Netzwerk, Projektarbeit', '2022', '2026', 2),
    ('education', 'Fachbereiche', 'ITP, SEW, INSY, MEDT',
     'Theorie und Praxis in verschiedenen IT-Fachgebieten', '2022', '2026', 3)
) as v(section_key, headline, subline, description, period_from, period_to, sort_order)
where s.section_key = 'education';

-- Kenntnisse
insert into public.cv_items (section_id, headline, subline, description, period_from, period_to, sort_order)
select s.id, v.headline, v.subline, v.description, v.period_from, v.period_to, v.sort_order
from public.cv_sections s
cross join (
  values
    ('skills', 'HTML, CSS, JavaScript', 'Frontend', 'Responsive Layouts, DOM, Fetch API', '', '', 1),
    ('skills', 'SQL / PostgreSQL', 'Supabase', 'Relationale Tabellen, JOINs, INSERT, SELECT', '', '', 2),
    ('skills', 'Java', 'SEW', 'Klassen, Vererbung, Interfaces, Datei-IO', '', '', 3),
    ('skills', 'Lua', 'Roblox', 'Game-Scripting, Events, Physik', '', '', 4),
    ('skills', 'Git, GitHub, Vercel', 'Tools', 'Versionskontrolle, CI/CD, Cloud-Deploy', '', '', 5)
) as v(section_key, headline, subline, description, period_from, period_to, sort_order)
where s.section_key = 'skills';

-- Sprachen
insert into public.cv_items (section_id, headline, subline, description, period_from, period_to, sort_order)
select s.id, v.headline, v.subline, v.description, v.period_from, v.period_to, v.sort_order
from public.cv_sections s
cross join (
  values
    ('languages', 'Deutsch', 'Muttersprache', 'Muendlich und schriftlich', '', '', 1),
    ('languages', 'Englisch', 'Schulisch', 'Technische Dokumentation lesen', '', '', 2),
    ('languages', 'Tuerkisch', 'Familiaer', 'Alltagskommunikation', '', '', 3)
) as v(section_key, headline, subline, description, period_from, period_to, sort_order)
where s.section_key = 'languages';

-- Rechte fuer API-Zugriff (Service Role nutzt bypass, aber sicher ist sicher)
grant usage on schema public to anon, authenticated, service_role;
grant all on all tables in schema public to service_role;
grant select on all tables in schema public to anon, authenticated;

-- Optional: RLS aus (einfacher fuer Schulprojekt mit Service Role Key)
alter table public.persons disable row level security;
alter table public.cv_sections disable row level security;
alter table public.cv_text_variants disable row level security;
alter table public.cv_items disable row level security;

-- Kontrolle
select 'persons' as tabelle, count(*) as anzahl from public.persons
union all
select 'cv_sections', count(*) from public.cv_sections
union all
select 'cv_text_variants', count(*) from public.cv_text_variants
union all
select 'cv_items', count(*) from public.cv_items;
